---
calendar_id: "pl1q0jmhbqqavhbtvi8km3m3lc@group.calendar.google.com"
drive_folder_id: "1mOsI_86qjgMkMk5vJZiV-FTRg-wIrtco"

editor: "nvim"
terminal: "kitty"
pdf_viewer: "zathura"

create_readme_file: true
highlight_current_course: true

notes_dir: "~/Documents/school-notes"
root: "~/Documents/school-notes/College/Year-2/fall"
templates_dir: "~/Documents/school-notes/College/Year-2/fall/_files"
current_course: "~/Documents/school-notes/current-course"

books_dir: "~/Documents/school-notes/current-course/books"
figures_dir: "~/Documents/school-notes/current-course/figures"

date_format: "%b %d %Y %a (%H:%M:%S)"
home: "/home/singularis"
user: "singularis"
trash_dir: "~/.local/share/lesson-manager/Year-2/fall"

assignments_dir: "~/Documents/school-notes/current-course/assignments"
assignment_folders:
  bib_folder: "my-assignments/bibtex-files"
  tex_folder: "my-assignments/latex-files"
  yaml_folder: "my-assignments/yaml-files"
  pdf_folder: "my-assignments/pdf-files"
  graded_assignment: "graded-assignments"
  online_assignment: "online-assignments"
  solution_key: "solution-keys/pdf-files"

rofi_options:
  - "-markup-rows"
  - "-kb-row-down"
  - "Down"
  - "-kb-custom-1"
  - "Ctrl+n"
  - "-no-fixed-num-lines"

folders:
  - "assignments"
  - "assignments/graded-assignments"
  - "assignments/online-assignments"
  - "assignments/solution-keys"
  - "assignments/solution-keys/pdf-files"
  - "assignments/solution-keys/latex-files"
  - "assignments/my-assignments"
  - "assignments/my-assignments/bibtex-files"
  - "assignments/my-assignments/image-files"
  - "assignments/my-assignments/latex-files"
  - "assignments/my-assignments/pdf-files"
  - "assignments/my-assignments/sympy-scripts"
  - "assignments/my-assignments/yaml-files"
  - "books"
  - "exam-review"
  - "figures"
  - "note-guide"
  - "papers"
  - "sympy-scripts"
  - "UltiSnips"

files:
  "assignments/my-assignments/preamble.tex": "symlink"
  "assignments/my-assignments/Makefile": "symlink"
  "assignments/solution-keys/Makefile": "symlink"
  "assignments/solution-keys/preamble.tex": "symlink"
  "Makefile": "symlink"
  "preamble.tex": "symlink"
  "UltiSnips/tex.snippets": "symlink"
  "assignments/my-assignments/master.tex": "copy"
  "assignments/solution-keys/master.tex": "copy"
  "intro.tex": "copy"
  "master.tex": "copy"
  "notes.md": "copy"
