calendar_id: "pl1q0jmhbqqavhbtvi8km3m3lc@group.calendar.google.com"

code_dir: "/home/singularis/Documents/school-setup"
editor: "nvim"
terminal: "xfce4-terminal"
terminal_commands: "-e"
pdf_viewer: "zathura"

notes_dir: "/home/singularis/Documents/school-notes"
root: "/home/singularis/Documents/school-notes/College/Year-1/winter"
templates_dir: "/home/singularis/Documents/school-notes/files/College/Year-1/winter"
current_course: "/home/singularis/Documents/school-notes/current-course"

assignments_dir: "/home/singularis/Documents/school-notes/current-course/assignments"
graded_assignments_folder: "/home/singularis/Documents/school-notes/current-course/assignments/graded-assignments"
my_assignments_folder: "/home/singularis/Documents/school-notes/current-course/assignments/my-assignments"
online_assignments_folder: "/home/singularis/Documents/school-notes/current-course/assignments/online-assignments"

my_assignments_image_folder: "/home/singularis/Documents/school-notes/current-course/assignments/my-assignments/latex-files"
my_assignments_bibtex_folder: "/home/singularis/Documents/school-notes/current-course/assignments/my-assignments/bibtex-files"
my_assignments_latex_folder: "/home/singularis/Documents/school-notes/current-course/assignments/my-assignments/latex-files"
my_assignments_yaml_folder: "/home/singularis/Documents/school-notes/current-course/assignments/my-assignments/yaml-files"
my_assignments_pdf_folder: "/home/singularis/Documents/school-notes/current-course/assignments/my-assignments/pdf-files"

date_format: "%b %d %Y %a (%H:%M:%S)"
home: "/home/singularis"
user: "singularis"

rofi_options:
  - "-lines"
  - "5"
  - "-markup-rows"
  - "-kb-row-down"
  - "Down"
  - "-kb-custom-1"
  - "Ctrl+n"

folders:
  - "assignments"
  - "assignments/graded-assignments"
  - "assignments/online-assignments"
  - "assignments/my-assignments"
  - "assignments/my-assignments/bibtex-files"
  - "assignments/my-assignments/image-files"
  - "assignments/my-assignments/latex-files"
  - "assignments/my-assignments/pdf-files"
  - "assignments/my-assignments/sympy-scripts"
  - "assignments/my-assignments/yaml-files"
  - "books"
  - "figures"
  - "lectures"
  - "papers"
  - "online-lecture-notes"
  - "sympy-scripts"
  - "UltiSnips"

files:
  "assignments/my-assignments/preamble.tex": "symlink"
  "Makefile": "symlink"
  "preamble.tex": "symlink"
  "assignments/my-assignments/master.tex": "copy"
  "intro.tex": "copy"
  "master.tex": "copy"
  "notes.md": "copy"
  "UltiSnips/tex.snippets": "copy"
